In [3]:
import numpy as np

a = np.arange(10)

b = np.split(a,[6])[0]
c = np.split(a,[6])[1]

print(a)
print(b)
print(c)

print(np.prod(c))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]
[6 7 8 9]
3024


In [27]:
import numpy as np
from numpy.random import normal
from numpy.linalg import norm
from numpy.linalg import svd
from numpy.linalg import pinv
from numpy.linalg import multi_dot
from numpy.linalg import det
from scipy.linalg import null_space
def hermitian(matrix):
    return np.conjugate(matrix.T)

sum = 0
res_sum = 0
for i in range(10000):
    a_real = normal(size=(2,4))
    a_imag = normal(size=(2,4))
    a = a_real + 1j * a_imag
    print(null_space(a))


    a_1 = np.hsplit(a,2)[0]
    a_2 = np.hsplit(a,2)[1]

    u_1, Lambda_1, vh_1 = svd(a_1)
    # print(Lambda_1)
    # print(multi_dot([
    #     hermitian(u_1),
    #     a_1,
    #     hermitian(vh_1),
    #     vh_1,
    #     hermitian(a_1),
    #     u_1
    # ]))

    w_1 = hermitian(vh_1)
    w_2 = multi_dot([pinv(a_2),a_1,w_1])

    w_2_norm = norm(w_2, 'fro')

    w_2_unit = w_2/w_2_norm

    # res_1 = np.dot(w_2, hermitian(w_2)) / w_2_norm ** 2
    # res_2 = np.dot(w_2_unit, hermitian(w_2_unit))

    res_1_matrix = multi_dot([
        hermitian(u_1),
        a_1,
        w_1,
        hermitian(w_1),
        hermitian(a_1),
        u_1  
    ])

    res_2_matrix = multi_dot([
        hermitian(u_1),
        a_1,
        w_2_unit,
        hermitian(w_2_unit),
        hermitian(a_1),
        u_1  
    ])
    
    res_sum += np.log2(1 + 1 / np.trace(np.dot(w_2,hermitian(w_2))) * det(res_2_matrix))
    
    sum += np.trace(np.dot(w_2,hermitian(w_2)))

# print(norm(w_2,'fro'))
# print(w_2)
# print(w_2_norm ** 2)
# print(det(res_1_matrix))
# print((np.dot(w_2_unit,hermitian(w_2_unit))))
# print(multi_dot([
#     hermitian(u_1),
#     a_2,
#     w_2,
#     hermitian(w_2),
#     hermitian(a_2),
#     u_1
# ]))
# Lambda_1_diag = np.diag(Lambda_1)
# print(np.dot(Lambda_1_diag,Lambda_1_diag))
# print(np.trace(np.dot(w_2,hermitian(w_2))))
print(sum / 10000)
print(res_sum/10000)
# sum = 0
# for i in range(10000):
#     sum += np.trace(np.dot(a_2,hermitian(a_2)))
# print(sum/10000)
# print(det(res_2_matrix))



(40.10828542028864+0j)
(0.1507555229401846-9.389044202450027e-19j)


In [167]:
import numpy as np
from numpy.random import normal
from numpy.linalg import norm
from numpy.linalg import svd
from numpy.linalg import pinv
from numpy.linalg import multi_dot
from numpy.linalg import det
from scipy.linalg import null_space
from numpy.linalg import eig
def hermitian(matrix):
    return np.conjugate(matrix.T)

a = np.zeros((2,2,3),dtype=complex)

sum_a = np.zeros((2,2),dtype=complex)
for i in range(3):
    a_real = normal(size=(2,2))
    a_imag = normal(size=(2,2))    
    a[:,:,i] = a_real + 1j * a_imag
    sum_a += a[:,:,i]

u, Lambda, vh = svd(sum_a)

v = hermitian(vh)
sum_lambda = np.zeros((2,2),dtype=complex)
for i in range(3):
    sum_lambda += multi_dot([
        hermitian(u),
        a[:,:,i],
        v,
        vh,
        hermitian(a[:,:,i]),
        u
        ])
    
lambda_sum = multi_dot([hermitian(u),sum_a,v,vh,hermitian(sum_a),u])
print(det(sum_lambda))
print(det(lambda_sum))

w, v = eig(a[:,:,0])

print(a[:,:,0] @ v)
print(w * v)
# print(np.dot(v, np.ones((2,2)) - w))


(191.1615033271055-6.773186234997404e-16j)
(105.91866640764697-5.153759597631901e-15j)
[[ 0.92117027+0.4477072j  -1.42300066+1.50718407j]
 [ 0.8815379 -0.1999043j   0.05048415-1.84533379j]]
[[ 0.92117027+0.4477072j  -1.42300066+1.50718407j]
 [ 0.8815379 -0.1999043j   0.05048415-1.84533379j]]


In [231]:
import numpy as np
from numpy.random import normal
from numpy.linalg import norm
from numpy.linalg import svd
from numpy.linalg import pinv
from numpy.linalg import multi_dot
from numpy.linalg import det
from scipy.linalg import null_space




def hermitian(matrix):
    return np.conjugate(matrix.T)

def db2watt(db):
    '''
    Unit Transform dBm to Watt
    input dB
    output Watt
    '''
    watt = 10 ** (db / 10)
    return watt

sum = 0
sum2= 0
sum3 = 0
K = 10 # db

# k = db2watt(K)
k = 0
# for i in range(10000):
h_nlos_real = normal(scale=np.sqrt(1/2),size=(2,3))
h_nlos_imag = normal(scale=np.sqrt(1/2),size=(2,3))
h_nlos = h_nlos_real + 1j * h_nlos_imag

h2_nlos_real = normal(scale=np.sqrt(1/2),size=(2,3))
h2_nlos_imag = normal(scale=np.sqrt(1/2),size=(2,3))
h2_nlos = h2_nlos_real + 1j * h2_nlos_imag

h_los = np.ones((2,3))
h2_los = np.ones((2,3))



h = np.sqrt(k / (k + 1)) * h_los + np.sqrt(1 / (k + 1)) * h_nlos
h2 = np.sqrt(k / (k + 1)) * h2_los + np.sqrt(1 / (k + 1)) * h2_nlos


u, Lambda, vh = svd(h)
u2, Lambda2, vh2 = svd(h2)

W = pinv(h)/norm(h,'fro')
W_2 = multi_dot([
    pinv(h),
    h2,
    hermitian(vh2)
    ]) / norm(multi_dot([
    pinv(h),
    h2,
    hermitian(vh2)
    ]), 'fro')
print(det(np.dot(h,W)))
print(det(np.dot(h,W_2)))
print(det(np.dot(h,hermitian(h))))
# h_1 = np.hsplit(h,2)[0]
# h_2 = np.hsplit(h,2)[1]
# print(np.dot(h_los,hermitian(h_los)))

# h_sum = h_1 + h_2

# sum += np.trace(np.dot(h_2,hermitian(h_2)))
# sum2 += np.trace(np.dot(h_nlos,hermitian(h_nlos)))
# sum3 += np.trace(np.dot(h_sum,hermitian(h_sum)))

# print(null_space(h_nlos).shape)
# print(np.dot(h_nlos,null_space(h_nlos)))

# a = np.trace(multi_dot([pinv(np.ones((2,3))), np.ones((2,3)), hermitian(np.ones((2,3)))]))
# print(a)
# print(np.trace(np.dot(np.ones((2,3)),np.ones((3,2)))))
# print(np.sqrt(k / (k + 1)) * a
#       + np.sqrt(1 / (k + 1)) * 6)
# print(sum/10000)
# print(sum2/10000)
# print(sum3/10000)
# (8.498383679533559+0j)


(-0.1503374312628771-0.31849027957040715j)


LinAlgError: Last 2 dimensions of the array must be square

In [234]:
#!/usr/bin/env python3
from functools import partial
from itertools import repeat
from multiprocessing import Pool, freeze_support

def func(c, a, b):
    return a + b + c

def main():
    counter = 0
    a_args = 1
    second_arg = 1
    third_arg = [1,2,3]
    with Pool(processes=4) as pool:
        # L = pool.starmap(func, [(1, 1), (2, 1), (3, 1)])
        # M = pool.starmap(func, zip(repeat(a_args), repeat(second_arg), third_arg))
        N = pool.map(partial(func, a=second_arg, b=a_args), third_arg)
        # assert L == M == N  
    print(N)
    # print(counter)
    pool.close()
if __name__=="__main__":
    freeze_support()
    main()

[3, 4, 5]


In [235]:
import numpy as np

a = np.diag(3)

print(a)

ValueError: Input must be 1- or 2-d.

In [ ]:
import numpy as np
from numpy.linalg import svd
from numpy.random import normal 
from numpy.linalg import multi_dot
from numpy.linalg import pinv
from numpy.linalg import norm

def hermitian(matrix):
    return np.conjugate(matrix.T)


sum = 0

# for i in range(100000):
a_real = normal(size=(2,4))
a_imag = normal(size=(2,4))

a = a_real + a_imag * 1j 

a_0 = np.hsplit(a,2)[0]
a_1 = np.hsplit(a,1)[0]

u_0, Lambda, vh_0 = svd(a_0)

v_0 = hermitian(vh_0)
w_0 = v_0
w_1 = multi_dot([pinv(a_1),a_0,w_0])
w_1_H = hermitian(w_1)
w_2 = w_1 / norm(w_1, 'fro') 
print(np.dot(w_1,hermitian(w_1)) * norm(w_1, 'fro') ** (-2))
print(np.dot(w_2,hermitian(w_2)))


[[0.13426085+0.j         0.18941118-0.04121006j]
 [0.18941118+0.04121006j 0.86573915+0.j        ]]
[[0.13426085+0.j         0.18941118-0.04121006j]
 [0.18941118+0.04121006j 0.86573915+0.j        ]]


In [ ]:
import numpy as np

a = 660

b = 19980

rate_a = 660 

rate_b = 19980

init = np.arange(30,3030,30)



In [ ]:
# import numpy as np

s = 1005

sum = 0
for i in range(1,s+1):
    sum += i ** 2
    # print(i)
print(sum)
if sum % 2 == 0:
    print('even number')
else:
    print('odd number')

338863555
odd number


In [ ]:
import numpy as np

from numpy.linalg import det
from lib.customize_func import dbm2watt


ps = dbm2watt(-15)
sigma = dbm2watt(-114)



print(a)

3.1622776601683795e-05


In [ ]:
import numpy as np
from lib.customize_func import db2watt

SNR = np.arange(-15,16,1)

zeta = 0.5

for SNR_index in range(len(SNR)):
    snr = db2watt(SNR[SNR_index])
    c = zeta * np.log2(1 + snr)
    print(c)

print(np.log10(135270)*10)

0.022457765509737878
0.02816046494326421
0.03527622200473686
0.0441357605202961
0.05513673133338146
0.06875176187496751
0.0855345692571989
0.10612237163019769
0.13123235357043883
0.16164966134692121
0.19820458058155693
0.24173747667284012
0.29305196322267374
0.35285952538675674
0.42172191260182623
0.5
0.5878183173461944
0.6850523348754931
0.7913411774557781
0.9061230956503127
1.0286866043033975
1.1582280898131299
1.2939071867810155
1.4348936095851426
1.580402211956512
1.7297158093186487
1.8821971835214308
2.0372926174527133
2.1945294836815226
2.3535101313644176
2.5139038366752597
51.31201490026233


In [ ]:
import numpy as np
from lib.customize_func import dbm2watt

a = -15
print(dbm2watt(a))

3.1622776601683795e-05


In [ ]:
import numpy as np

a = np.array([])

a = np.append(a,1)
a = np.append(a,2)

print(a)

[1. 2.]


In [ ]:
import numpy as np
import cupy as cp

a = cp.array([1,0,3,4,5,5,0,0,0,0,0,0])

print(a)
a = a[a != 0]
print(a)

[1 0 3 4 5 5 0 0 0 0 0 0]
[1 3 4 5 5]


In [ ]:
import itertools as it
import numpy as np


stuff = np.array([1, 2, 3, 4])
# for L in range(len(stuff)+1):
# i = 0
for subset in it.combinations(stuff, 2):
    # i += 1
    not_in_subset = np.array([i for i in stuff if i not in subset])
    for j in range(len(subset)):
        print(subset)
    print(not_in_subset)

print(np.diag(np.sqrt(stuff)))
# print(subset) 

(1, 2)
(1, 2)
[3 4]
(1, 3)
(1, 3)
[2 4]
(1, 4)
(1, 4)
[2 3]
(2, 3)
(2, 3)
[1 4]
(2, 4)
(2, 4)
[1 3]
(3, 4)
(3, 4)
[1 2]
[[1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]
 [0.         0.         0.         2.        ]]


In [ ]:
import numpy as np

a = np.arange(1,4)

b = np.zeros([3,3])

for i in range(3):
    b[i] = np.ones(3) * a[i]
    
print(b)

b = b.reshape(9)

print(b)

b = np.diag(b)

print(b)

b = np.sqrt(b)

print(b)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[1. 1. 1. 2. 2. 2. 3. 3. 3.]
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3.]]
[[1.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         1.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         1.41421356 0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         1.41421356 0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         1.41421356
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.73205081 0.    

In [189]:
import numpy as np
import numpy.linalg as LG

a = np.array([[1,0],[-1/2,1]])

w, x = LG.eig(a)

print(a * x[:,0])
print(w[0] * np.eye(2) * x[:,0])
print(LG.matrix_rank(a))

[[ 0.  0.]
 [-0.  1.]]
[[0. 0.]
 [0. 1.]]
2


In [225]:
import numpy as np
from numpy.random import normal
from numpy.linalg import norm
from numpy.linalg import pinv
from numpy.linalg import det
sum = 0
for i in range(10000):
    a_real = normal(loc=0.0,scale=np.sqrt(1/2),size=(2,2))
    a_imag = normal(loc=0.0,scale=np.sqrt(1/2),size=(2,2))

    a = a_real + 1j * a_imag

    W = pinv(a)/(norm(a,'fro'))

    sum += det(np.dot(a,W))
print(sum/10000)

(0.33210101786246127+4.489402266506353e-19j)


In [ ]:
import numpy as np
from numpy.random import normal
from numpy.linalg import norm
from numpy.linalg import pinv
from numpy.linalg import det

def hermitian(matrix):
    return np.conjugate(matrix.T)



a_real = normal(loc=0.0,scale=np.sqrt(1/2),size=(2,2))
a_imag = normal(loc=0.0,scale=np.sqrt(1/2),size=(2,2))


a_nlos = a_real + 1j * a_imag



In [3]:
import numpy as np

a = np.min([1,2])

print(a)

1


In [146]:
import numpy as np
from numpy.random import normal
from numpy.linalg import qr
from numpy.linalg import svd
from numpy.linalg import det

from lib.customize_func import dbm2watt

def hermitian(matrix):
    return np.conjugate(matrix.T)

P = 10 # dbm
sigma = -114 # dbm


sigma_u = dbm2watt(sigma)
p = dbm2watt(P)

a_x = normal(loc = 0, scale= np.sqrt(1/2),size=(4,10))
a_y = normal(loc = 0, scale= np.sqrt(1/2),size=(4,10))

a_nlos = a_x + 1j * a_y

q, r = qr(a_nlos)

u, Sigma, vh = svd(a_nlos)
if a_nlos.shape[0] > a_nlos.shape[1]:
    Sigma = np.append(Sigma, np.zeros(int(np.abs(a_nlos.shape[0] - a_nlos.shape[1]))))
Sigma_matrix = np.diag(Sigma)


print(np.log2(det(np.eye(a_nlos.shape[0]) + p/(4 * sigma_u) * np.dot(Sigma_matrix,Sigma_matrix))))
print(np.log2(det(np.eye(a_nlos.shape[0]) + p/(4 * sigma_u) * np.dot(a_nlos,hermitian(a_nlos)))))
print(np.log2(det(np.eye(a_nlos.shape[0]) + p/(4 * sigma_u) * np.dot(r,hermitian(r)))))

169.21561720451564
(169.2156172045156+2.839916982146123e-17j)
(169.2156172045156-2.302692940474929e-17j)


In [ ]:
import numpy as np

from scipy.special import erf

def gaussian_q(x):
    0.5 - 0.5 * erf(x/np.sqrt(2)) 
    



# print(0.5 - 0.5 * erf())