In [22]:
import numpy as np

from numpy.random import normal
from numpy.linalg import qr
from numpy.linalg import svd
from numpy.linalg import matrix_rank

a = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
c = np.array([[4,3,2,1],[4,3,2,1],[4,3,2,1]])
b = normal(size=(3,4))

u,Lambda,vh = svd(b)

print(np.dot(a,vh.T))
print(matrix_rank(vh))
print(b)

[[-2.00505882e+00 -2.85288451e-03 -1.38647480e+00  4.90483625e+00]
 [-2.00505882e+00 -2.85288451e-03 -1.38647480e+00  4.90483625e+00]
 [-2.00505882e+00 -2.85288451e-03 -1.38647480e+00  4.90483625e+00]]
4
[[ 0.13537833  1.13170851  0.17344    -0.49662321]
 [ 0.96045295  0.55310006  1.19336949 -1.39990057]
 [ 0.83671697  2.36115596 -1.14576674  0.97730585]]
