In [4]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import svd

from lib.customize_func import channel_vector
from lib.customize_func import hermitian
import matplotlib.pyplot as plt

Tx = 4
Rx = 4

# H = channel_vector(Tx,Rx,1,1,'rayleigh')

R = np.arange(0,5,0.1)

out_anal = np.zeros(len(R))
out_simu = np.zeros(len(R))
out_simu2 = np.zeros(len(R))

simulation_time = 1000

for r_index in range(len(R)):

    out_anal[r_index] = (1 - np.exp(-R[r_index]))**(Tx * Rx)

    counter = 0
    counter_2 = 0
    for i in range(simulation_time):
        H = channel_vector(Tx,Rx,1,1,'rayleigh')
        C_simu = np.log2(np.abs(det(np.eye(Rx)+np.dot(H, hermitian(H)))))

        if C_simu < R[r_index]:
            counter += 1
        

        C_simu_2 = 0
        u, Lambda, v_h = svd(np.dot(H,hermitian(H)))
        for _ in range(len(Lambda)):
            C_simu_2 += np.log2(1 + Lambda[_])
        
        if C_simu_2 < R[r_index]:
            counter_2 = 0


        print(C_simu)
        print(C_simu_2)

    # print(out_simu[r_index])
    # print(out_simu2[r_index])
# print(out_simu)



6.6928485804884446
6.692848580488445
7.0599239627897665
7.059923962789766
7.066713288605863
7.066713288605862
8.780292228641239
8.780292228641239
5.99755816819561
5.997558168195611
8.056565166601828
8.056565166601828
5.745125468829545
5.745125468829544
6.7802759850772585
6.78027598507726
8.360053620903502
8.360053620903502
8.334729980968852
8.334729980968852
7.8731645350998445
7.873164535099843
7.955974914154044
7.955974914154045
7.882619140163745
7.882619140163743
6.961598081668351
6.961598081668351
7.6598221131086275
7.65982211310863
6.697540451338194
6.697540451338193
5.0720079619223295
5.07200796192233
6.168480614251087
6.168480614251086
8.216312894493319
8.216312894493319
7.493444535640594
7.493444535640596
6.792638447308787
6.792638447308783
8.07930756305808
8.079307563058082
8.835527483661036
8.835527483661036
7.973991784270249
7.973991784270249
7.010664004989713
7.010664004989712
8.133828486516766
8.133828486516768
9.495074495655766
9.495074495655766
7.7754228706759525
7.775422

In [35]:
import numpy as np 

from numpy.linalg import det
from numpy.linalg import svd
from numpy.linalg import qr
from numpy.linalg import eigvals
from numpy.linalg import norm
from numpy.linalg import pinv
from numpy.linalg import inv

from lib.customize_func import channel_vector
from lib.customize_func import hermitian
from lib.customize_func import db2watt
from par_lib import par_lib


tx = 3
rx = 5
# h_nlos = channel_vector(tx,rx,1,0,'rician',K=db2watt(20.0),f=6e8,d=[100.0])
h_nlos = channel_vector(tx,rx,1,0,'rayleigh')

# print(h_nlos)
q, r = qr(h_nlos,'complete')
q1, r1 = qr(h_nlos)
u, Lambda, vh = svd(h_nlos)

# print(np.sum(np.diag(r) ** 2))
# print(np.sum(Lambda ** 2))
# print(np.dot(h_nlos,hermitian(h_nlos)))

if rx > tx:
    Lambda = np.append(Lambda,np.zeros(rx-tx))

Lambda_diag = np.diag(Lambda)

print(np.sum(np.dot(Lambda_diag,Lambda_diag)))
print(np.sum(np.abs(eigvals((np.dot(h_nlos,hermitian(h_nlos)))))))
print(np.dot(q,hermitian(q)))

print(np.abs(det(np.eye(rx) + 4 * np.dot(h_nlos,hermitian(h_nlos)))))
print(np.abs(det(np.eye(rx) + 4 * np.dot(Lambda_diag,hermitian(Lambda_diag)))))
print(np.abs(det(np.eye(rx) + 4 * np.dot(r,hermitian(r)))))



13.721903137652987
13.721903137652971
[[ 1.00000000e+00+0.00000000e+00j -6.93889390e-17+6.93889390e-17j
  -1.94289029e-16+2.35922393e-16j  4.16333634e-17+4.16333634e-17j
  -1.60645012e-17-1.37699347e-16j]
 [-6.93889390e-17-6.93889390e-17j  1.00000000e+00+0.00000000e+00j
   5.55111512e-17-2.77555756e-17j  4.16333634e-17+9.54097912e-17j
  -1.53730893e-16-3.02714942e-17j]
 [-1.94289029e-16-2.35922393e-16j  5.55111512e-17+2.77555756e-17j
   1.00000000e+00+0.00000000e+00j  0.00000000e+00+6.93889390e-18j
   2.24551885e-17+1.97101943e-17j]
 [ 4.16333634e-17-4.16333634e-17j  4.16333634e-17-9.54097912e-17j
   0.00000000e+00-6.93889390e-18j  1.00000000e+00+0.00000000e+00j
  -8.34524702e-18+2.00586534e-17j]
 [ 5.55111512e-17+1.24900090e-16j -1.11022302e-16+2.77555756e-17j
   2.77555756e-17+0.00000000e+00j -1.73472348e-17-5.55111512e-17j
   1.00000000e+00-7.17964644e-18j]]
1966.835541790177
1966.835541790176
1966.8355417901741


In [10]:
import numpy as np

from numpy.linalg import det
from numpy.linalg import svd
from numpy.linalg import qr
from numpy.linalg import eigvals

a = np.array([[1,2],[2,1]])

q, r = qr(a,'complete')
u, Lambda, vh = svd(a)

print((np.dot(a,hermitian(a))))
print(np.sum(np.dot(Lambda_diag,Lambda_diag)))
print(np.sum(np.abs(eigvals((np.dot(a,hermitian(a)))))))

[[5 4]
 [4 5]]
5.040250022952379
10.0


In [26]:
import numpy as np

from numpy.random import normal

a = 0
sum = 0
for loop in range(100000):
    real = normal(loc=0,scale=1/np.sqrt(2),size=None)
    imag = normal(loc=0,scale=1/np.sqrt(2),size=None)
    a = real + 1j * imag
    sum += np.abs(a) ** 2 

sum = sum / 100000
print(sum)

0.9992888278640867


In [29]:
import numpy as np

from numpy.linalg import det

def channel(matrix_size):
    real = normal(loc=0,scale=1/np.sqrt(2),size=matrix_size)
    imag = normal(loc=0,scale=1/np.sqrt(2),size=matrix_size)
    a = real + 1j * imag
    return a

def hermitian(matrix):
    return np.conjugate(matrix.T)


a = channel((2,2))
aa = np.dot(a,hermitian(a))



print(aa)

[[ 1.45003048+5.40270407e-17j -0.33359157-5.61094759e-01j]
 [-0.33359157+5.61094759e-01j  0.31598245-2.58817400e-18j]]


In [1]:
import platform

print(platform.system())

Linux


In [14]:
import numpy as np
from numpy.linalg import multi_dot

a = np.ones(2).reshape(1,2)

H = np.arange(1,9).reshape(2,4)

W = np.eye(4)

x = np.ones(4).reshape(4,1)
print(H)
print(W)
print(multi_dot([H,W]))

[[1 2 3 4]
 [5 6 7 8]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [55]:
import numpy as np
from numpy.linalg import norm
from numpy.random import normal

def channel(matrix_size):
    real = normal(loc=0,scale=1/np.sqrt(2),size=matrix_size)
    imag = normal(loc=0,scale=1/np.sqrt(2),size=matrix_size)
    result = real + 1j * imag
    return result

def hermitian(matrix):
    return np.conjugate(matrix.T)

a = channel((2,2))
b = channel((2,2))

w = abs(a + b) / (a+b)

print(w*np.conjugate(w))
ang = np.arctan(a.real/a.imag)

print(a * w * np.conjugate(a * w))
print(a)
print(w)

[[1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]]
[[2.33816369+0.j 0.00582129+0.j]
 [0.71938233+0.j 0.46448267+0.j]]
[[-1.11827274-1.04289489j  0.06742215+0.03571476j]
 [ 0.02454599+0.84780884j -0.45586252+0.5066281j ]]
[[-0.82128054-0.57052457j -0.0961591 +0.99536598j]
 [ 0.4332677 -0.90126528j -0.79061502-0.61231356j]]


In [ ]:
import numpy as np

import sys

from lib.customize_func import gaussian_approximation_su

from par_lib import par_lib
def channel(matrix_size):
    real = normal(loc=0,scale=1/np.sqrt(2),size=matrix_size)
    imag = normal(loc=0,scale=1/np.sqrt(2),size=matrix_size)
    result = real + 1j * imag
    return result


def main(argv):
    
    P_min = par_lib.P_min
    P_max = par_lib.P_max
    P_inst = par_lib.P_inst
    R_s = par_lib.R_s
    zeta = par_lib.zeta
    Sigma = par_lib.sigma
    Sigma_e = par_lib.sigma_e    
    
    
    analy = 1 - gaussian_approximation_su(2, 2, p_s / K_s)


if __name__ == '__main__':
    main(sys.argv[1:])

In [13]:
import numpy as np

a = np.arange(20).reshape(10,2)

b = np.arange(20)
print(a)
print(np.sum(a,1))
print(np.sum(b))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[ 1  5  9 13 17 21 25 29 33 37]
190


In [71]:
import numpy as np
from numpy.linalg import norm
from numpy.random import normal
def channel(matrix_size):
    real = normal(loc=0,scale=1/np.sqrt(2),size=matrix_size)
    imag = normal(loc=0,scale=1/np.sqrt(2),size=matrix_size)
    result = real + 1j * imag
    return result

def hermitian(matrix):
    return np.conjugate(matrix.T)

a = channel((2,3))
# a = np.ones((5,4))
print(np.dot(a,hermitian(a)))
print(np.trace(np.dot(hermitian(a),a)))
print(norm(a,'fro') ** 2)


[[2.08254563e+00+4.14415906e-18j 8.11822606e-03-3.61557322e+00j]
 [8.11822606e-03+3.61557322e+00j 8.55462353e+00+1.76446086e-16j]]
(10.637169158135857-1.809120755410855e-16j)
10.63716915813586


In [4]:
import numpy as np
from numpy.linalg import matrix_rank as rank

a = np.array([[3,4],[3,4]])

print(a)
a = a.reshape(4)
print(a)
print(rank(a))

[[3 4]
 [3 4]]
[3 4 3 4]
1


In [13]:
import numpy as np


matrix_shape = (2,0)
re = np.random.normal(0,np.sqrt(1/2),size=matrix_shape)
im = np.random.normal(0,np.sqrt(1/2),size=matrix_shape)
        
result = re + 1j * im

print(result)

[]


In [1]:
import numpy as np

a = np.zeros([3,3])
a[0][0] = 1
a[1][0] = 1

a = np.trace(np.dot(a,a.T))

print(a)

2.0
